id: Pwned v2 test
version: 3
name: Pwned v2 test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: fb4b8937-4f44-4c67-8cc0-69d967511dfb
    type: start
    task:
      id: fb4b8937-4f44-4c67-8cc0-69d967511dfb
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: c1a42a34-75fb-4a8f-8a3c-e761370c8633
    type: regular
    task:
      id: c1a42a34-75fb-4a8f-8a3c-e761370c8633
      version: -1
      name: Get email
      description: Checks if an email has been compromised, as part of previous breaches.
      script: Have I Been Pwned? V2|||email
      type: regular
      iscommand: true
      brand: Have I Been Pwned? V2
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      email:
        simple: example@demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: d3a38a11-af4b-48a6-8507-e86a0a3f6b1d
    type: regular
    task:
      id: d3a38a11-af4b-48a6-8507-e86a0a3f6b1d
      version: -1
      name: Get domain
      description: Checks if domain has been compromised.
      script: Have I Been Pwned? V2|||domain
      type: regular
      iscommand: true
      brand: Have I Been Pwned? V2
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      domain:
        simple: adobe.com
      fullResponse: {}
      include_inactive: {}
      long: {}
      retries: {}
      sampleSize: {}
      threshold: {}
      wait: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 25e9274b-81b2-46cc-8314-8f4dde821a55
    type: condition
    task:
      id: 25e9274b-81b2-46cc-8314-8f4dde821a55
      version: -1
      name: Check domain dBot score
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: DBotScore.Score
            iscontext: true
          right:
            value:
              simple: "2"
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
          right:
            value:
              simple: adobe.com
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Type
            iscontext: true
          right:
            value:
              simple: domain
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Vendor
            iscontext: true
          right:
            value:
              simple: Have I Been Pwned? V2
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 8e04d2d5-c3e7-4758-8d92-c235c8c91cfc
    type: condition
    task:
      id: 8e04d2d5-c3e7-4758-8d92-c235c8c91cfc
      version: -1
      name: Check email dBot score
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              simple: DBotScore.Score
            iscontext: true
          right:
            value:
              simple: "0"
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
          right:
            value:
              simple: example@demisto.com
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Type
            iscontext: true
          right:
            value:
              simple: email
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Vendor
            iscontext: true
          right:
            value:
              simple: Have I Been Pwned? V2
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 08b6b6c1-9bb8-4123-806d-44b72838c1fb
    type: title
    task:
      id: 08b6b6c1-9bb8-4123-806d-44b72838c1fb
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 7dd161c5-465a-4426-8be8-10b882a4f103
    type: regular
    task:
      id: 7dd161c5-465a-4426-8be8-10b882a4f103
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 4aac312a-7d24-4048-836e-17f3dbc0d907
    type: regular
    task:
      id: 4aac312a-7d24-4048-836e-17f3dbc0d907
      version: -1
      name: check email indicator regex (auto enrich)
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      value:
        simple: bt53h6htyj8j57k9k=organization.org@ozzy.qwer.de
    reputationcalc: 2
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 3861fcaa-c145-415d-8767-3a100212361d
    type: regular
    task:
      id: 3861fcaa-c145-415d-8767-3a100212361d
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: d2690f57-0a39-4074-80a2-666d7bc41429
    type: condition
    task:
      id: d2690f57-0a39-4074-80a2-666d7bc41429
      version: -1
      name: Check email with `=` in DBotScore
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
          right:
            value:
              simple: bt53h6htyj8j57k9k=organization.org@ozzy.qwer.de
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Vendor
            iscontext: true
          right:
            value:
              simple: Have I Been Pwned? V2
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 6ad7fe5f-fd48-4fff-8832-ee0280cc9335
    type: regular
    task:
      id: 6ad7fe5f-fd48-4fff-8832-ee0280cc9335
      version: -1
      name: Get Email2
      description: Checks if an email has been compromised, as part of previous breaches.
      script: Have I Been Pwned? V2|||email
      type: regular
      iscommand: true
      brand: Have I Been Pwned? V2
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      email:
        simple: joe@gmail.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 97cbdc07-8340-482d-88f2-cb113f45d5bf
    type: condition
    task:
      id: 97cbdc07-8340-482d-88f2-cb113f45d5bf
      version: -1
      name: Check email domains
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsString
          left:
            value:
              complex:
                root: Account
                accessor: Email.Pwned-V2.Compromised.Reporters
            iscontext: true
          right:
            value:
              simple: 000webhost
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 70e5181c-84ad-492d-84f9-e9eb7946bc96
    type: regular
    task:
      id: 70e5181c-84ad-492d-84f9-e9eb7946bc96
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: da4e1fb6-b0bd-4c37-8161-c925ce581b4f
    type: condition
    task:
      id: da4e1fb6-b0bd-4c37-8161-c925ce581b4f
      version: -1
      name: Check paste
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsString
          left:
            value:
              simple: Account.Email.Pwned-V2.Compromised.Reporters
            iscontext: true
          right:
            value:
              simple: Pastebin
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: a9f33d71-41d2-4884-88a3-87491b93bec6
    type: regular
    task:
      id: a9f33d71-41d2-4884-88a3-87491b93bec6
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      seconds:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: fcc322b0-b9bb-4285-8f06-d0262c470c6e
    type: regular
    task:
      id: fcc322b0-b9bb-4285-8f06-d0262c470c6e
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      seconds:
        simple: "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: 42649a4c-60e4-4bbf-882c-4af798635e58
    type: regular
    task:
      id: 42649a4c-60e4-4bbf-882c-4af798635e58
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      seconds:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 12249bb6-38df-47f0-8483-21e3d5273172
    type: regular
    task:
      id: 12249bb6-38df-47f0-8483-21e3d5273172
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      seconds:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "6_10_yes": 0.89
    },
    "paper": {
      "dimensions": {
        "height": 3010,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
