id: JsonWhoIs-Test
version: -1
name: JsonWhoIs-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f041b439-d8ea-4921-8a82-689aaf13ceda
    type: start
    task:
      id: f041b439-d8ea-4921-8a82-689aaf13ceda
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 905a6c40-955e-43a3-83b3-2181ee1562c3
    type: regular
    task:
      id: 905a6c40-955e-43a3-83b3-2181ee1562c3
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: b004aa51-537e-4242-8f78-b2f66b5fb6d9
    type: regular
    task:
      id: b004aa51-537e-4242-8f78-b2f66b5fb6d9
      version: -1
      name: whois
      description: Provides data enrichment for Domains, URLs, and IP addresses.
      script: JsonWhoIs|||whois
      type: regular
      iscommand: true
      brand: JsonWhoIs
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      query:
        simple: demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 86eac723-efa2-469e-8403-9a196225a815
    type: condition
    task:
      id: 86eac723-efa2-469e-8403-9a196225a815
      version: -1
      name: Validate parameters
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Domain.WHOIS.DomainStatus
            iscontext: true
        - operator: isExists
          left:
            value:
              simple: Domain.WHOIS.ExpirationDate
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Domain.WHOIS.CreationDate
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 464e80ef-b861-4638-811e-275639ffbc16
    type: regular
    task:
      id: 464e80ef-b861-4638-811e-275639ffbc16
      version: -1
      name: Close incident
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 845,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
