version: 2
jobs:
  build:
    docker:
      - image: devdemisto/content-build-2and3:2.0.0.1785  # disable-secrets-detection
    resource_class: medium+
    environment:
      CONTENT_VERSION: "19.10.0"
      SERVER_VERSION: "5.0.0"
      GIT_SHA1: "f2e65c13c84a348d0d8c52804a45398a4639afee" # guardrails-disable-line disable-secrets-detection
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Environment
          when: always
          command: |
              echo 'export CIRCLE_ARTIFACTS="/home/circleci/project/artifacts"' >> $BASH_ENV
              echo 'export PATH="/home/circleci/.pyenv/shims:/home/circleci/.local/bin:/home/circleci/.pyenv/bin:${PATH}"' >> $BASH_ENV # disable-secrets-detection
              echo 'export PYTHONPATH="/home/circleci/project:${PYTHONPATH}"' >> $BASH_ENV
              echo "=== sourcing $BASH_ENV ==="
              source $BASH_ENV
              sudo mkdir -p -m 777 $CIRCLE_ARTIFACTS
              chmod +x ./Tests/scripts/*
              chmod +x ./Tests/lastest_server_build_scripts/*
              pyenv versions
              python --version
              python3 --version
              pip install pyminizip
              pip3 install pyminizip
              echo "Parameters: NIGHTLY: $NIGHTLY, NON_AMI_RUN: $NON_AMI_RUN, SERVER_BRANCH_NAME: $SERVER_BRANCH_NAME"
      - add_ssh_keys:
          fingerprints:
              - "02:df:a5:6a:53:9a:f5:5d:bd:a6:fc:b2:db:9b:c9:47" # disable-secrets-detection
              - "f5:25:6a:e5:ac:4b:84:fb:60:54:14:82:f1:e9:6c:f9" # disable-secrets-detection
      - run:
          name: Create ID Set
          when: always
          command: |
            touch file1.log
            echo "hello world" > file2.log
            echo "py2:"
            python2 Tests/scripts/test.py $CIRCLE_ARTIFACTS/Logs2.zip
            echo "py3:"
            python3 Tests/scripts/test.py $CIRCLE_ARTIFACTS/Logs3.zip

      - store_artifacts:
          path: artifacts
          destination: artifacts
          when: always

workflows:
  version: 2
  commit:
    jobs:
      - build
