id: Traps Quarantine Event
version: -1
name: Traps Quarantine Event
starttaskid: "0"
description: "Use this playbook to quarantine events"
fromversion: ""
tasks:
  "0":
    id: "0"
    taskid: 44e6be24-0679-4215-8a65-19828edd4095
    type: start
    task:
      id: 44e6be24-0679-4215-8a65-19828edd4095
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 19b66798-0d90-4a2d-80f9-3805f3078d2f
    type: playbook
    task:
      id: 19b66798-0d90-4a2d-80f9-3805f3078d2f
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${Traps.QuarantineResult.OperationID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: operation_id
      PollingCommandName:
        simple: traps-event-quarantine-result
      Timeout:
        simple: "10"
      dt:
        simple: Traps.QuarantineResult(val.Status == 'pending' || val.Status == 'in
          progress').OperationID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 262c4355-e405-42f8-8cde-87fd4c365298
    type: regular
    task:
      id: 262c4355-e405-42f8-8cde-87fd4c365298
      version: -1
      name: traps-event-quarantine
      description: Creates a quarantine entry for the specified event.
      script: Traps|||traps-event-quarantine
      type: regular
      iscommand: true
      brand: Traps
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      event_id:
        simple: ${inputs.event_id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 60a06839-9d41-4a34-8783-1ef2a3d256df
    type: regular
    task:
      id: 60a06839-9d41-4a34-8783-1ef2a3d256df
      version: -1
      name: traps-event-quarantine-result
      description: Returns the result of the specified quarantine operation.
      script: '|||traps-event-quarantine-result'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      operation_id:
        simple: ${Traps.Quarantine.OperationID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 28ffa98b-7c00-41d7-8bee-cce19b7f11c8
    type: regular
    task:
      id: 28ffa98b-7c00-41d7-8bee-cce19b7f11c8
      version: -1
      name: traps-event-quarantine-result
      description: Returns the result of the specified quarantine operation.
      script: Traps|||traps-event-quarantine-result
      type: regular
      iscommand: true
      brand: Traps
    scriptarguments:
      operation_id:
        simple: ${Traps.Quarantine.OperationID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: event_id
  value: {}
  required: false
  description: Event ID
outputs: []
