id: DBot_Create_URL_Classifier
version: -1
name: DBot Create URL Classifier
description: |-
  Create URL Classifier using machine learning - a wrapper to the training playbook.
  You can use as scheduled job.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7ea4ac9b-13c7-47d3-893f-f998320df1e7
    type: start
    task:
      id: 7ea4ac9b-13c7-47d3-893f-f998320df1e7
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 4c6cd9bf-b1cd-47cf-8d56-7e81331b0ecc
    type: playbook
    task:
      id: 4c6cd9bf-b1cd-47cf-8d56-7e81331b0ecc
      version: -1
      name: DBot Train URL Classifier
      description: Create a machine learning URL classifier based on URL indicators
        score in Demisto.
      playbookName: DBot Train URL Classifier
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      maxIndicators:
        simple: "10000"
      modelAccuracyThreshold:
        simple: "0"
      modelName:
        simple: url
      overrideModel:
        simple: "true"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 73729840-f9f2-424e-8b31-553355472a48
    type: regular
    task:
      id: 73729840-f9f2-424e-8b31-553355472a48
      version: -1
      name: Close Incident
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: b70e31b3-04b2-43d1-80f9-d152fe6c4000
    type: title
    task:
      id: b70e31b3-04b2-43d1-80f9-d152fe6c4000
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 4.1.0
tests:
  - DBot_Train_URL_Classifier