id: Traps Isolate Endpoint
version: -1
name: Traps Isolate Endpoint
starttaskid: "0"
description: "Use this playbook to isolate endpoints"
fromversion: ""
tasks:
  "0":
    id: "0"
    taskid: 44e6be24-0679-4215-8a65-19828edd4095
    type: start
    task:
      id: 44e6be24-0679-4215-8a65-19828edd4095
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 40b681a4-91a1-4df0-8dcd-6d40cae0e052
    type: regular
    task:
      id: 40b681a4-91a1-4df0-8dcd-6d40cae0e052
      version: -1
      name: traps-endpoint-isolate
      description: Isolates the specified endpoint.
      script: Traps|||traps-endpoint-isolate
      type: regular
      iscommand: true
      brand: Traps
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      endpoint_id:
        simple: ${inputs.endpoint_id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: c38dc0d1-caa8-4fa6-8387-dd03369dbc23
    type: regular
    task:
      id: c38dc0d1-caa8-4fa6-8387-dd03369dbc23
      version: -1
      name: traps-endpoint-isolate-status
      description: Returns the status of the specified endpoint isolate operation.
      script: Traps|||traps-endpoint-isolate-status
      type: regular
      iscommand: true
      brand: Traps
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      operation_id:
        simple: ${Traps.Isolate.OperationID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 6404aab9-9ed0-4aa6-8fbb-1d5b6cd463ce
    type: playbook
    task:
      id: 6404aab9-9ed0-4aa6-8fbb-1d5b6cd463ce
      version: -1
      name: GenericPolling
      description: ""
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${Traps.Isolate.OperationID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: operation_id
      PollingCommandName:
        simple: traps-endpoint-isolate-status
      Timeout:
        simple: "10"
      dt:
        simple: Traps.IsolateResult(val.Status == 'pending' || val.Status == 'in progress').OperationID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 4bfe54ba-fb7a-4a5e-8e31-8be1f5e0ccd4
    type: regular
    task:
      id: 4bfe54ba-fb7a-4a5e-8e31-8be1f5e0ccd4
      version: -1
      name: traps-endpoint-isolate-status
      description: Returns the status of the specified endpoint isolate operation.
      script: Traps|||traps-endpoint-isolate-status
      type: regular
      iscommand: true
      brand: Traps
    scriptarguments:
      operation_id:
        simple: ${Traps.IsolateResult.OperationID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: endpoint_id
  value: {}
  required: false
  description: Endpoint ID
outputs: []
tests:
  - No tests - Cannot test this as we have no reversble cpmmand